---
config:
  theme: neutral
  look: classic
  layout: dagre
---
flowchart LR
 subgraph Project["Web app project"]
        App["TS/JS files"]
        Config["power.config.json"]
        SDK["Power Apps SDK"]
        Models["SDK generated<br>Models &amp; Services"]
  end
    CLI["Power Platform CLI"] --> Project & Services["Power Platform Services"]
    App --> SDK & Models
    SDK --> Config
    SDK <--> Models & Connectors["Power Platform Connectors"]