---
config:
  theme: neutral
  look: classic
  layout: dagre
---
flowchart TB
 subgraph Assets["Assets to run a code app"]
  direction TB
  YourCode["Your code"]
  SDK["Power Apps SDK"]
  Host["Power Apps host"]
  YourCode --> SDK --> Host
 end
 subgraph MS["Microsoft Services"]
  direction TB
  Connectors["Power Platform connectors"]
  Services["Power Platform Services"]
  Entra["Microsoft Entra"]
  Admin["Power Platform Admin Center"]
  Connectors <-->Services
 end
 Host --> Services
 Host --> Connectors
 Host --> Entra
 Admin --> Services
 Admin --> Connectors